
fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /resetting
app.swagger_ui:
  path: /doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
app.swagger:
  path: /api/doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }

